config/routes.rb
Myapp::Application.routes.draw do
  devise_for :users

  root :to => 'staticpages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
   attr_accessible :hour, :emotion, :learned, :image

 mount_uploader :image, PictureUploader


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	# new
	def new
		#hello ruby code here
		@pic = Pic.new
	end

	def create
		@pic = Pic.create(params[:pic])
		redirect_to pics_path
	end

	def index
		@pics = Pic.all
	end

	def show
	end

	def destroy
	end

	def edit
	end

	def update
	end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
	  <div class="navbar-inner">
		    <div class="container">
		 
		      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </a>
		 
		      <!-- Be sure to leave the brand out there if you want it shown -->
		      <%= link_to 'The Great Ruby Bandit', root_path, :class => 'brand' %>
		 
		      <!-- Everything you want hidden at 940px or less, place within here -->
		      <div class="nav-collapse collapse">

		      	<ul class="nav">
		      		<li> 
		      			<%= link_to('My App', pics_path) %>
		      		</li>
		      		
					
		      		<% if current_user.blank? %>
		      		<li>
		      			<%= link_to('Signin', new_user_session_path) %>
		      		</li>
		      		<li>
		      			<%= link_to('Register', new_user_registration_path) %>
		      		</li>
		      			<% else %>
		      			<li>
		      			<%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
		      		</li>
		      			<% end %>	

		      			<%= link_to 'New Pic', new_pic_path,
		      			:class => 'btn btn-success' %>
		      	</ul>

		        <!-- .nav, .navbar-search, .navbar-form, etc -->
		      </div>
		 
		    </div>
	  </div>
</div>
		<% if notice.present? %>
		<p class="notice"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
       	<p class="alert"><%= alert %></p>
       	<% end %>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
		<h2 class="custom-pic-header"> FOOL! No rubies here! But stay tune to continue the adventure...</h2>

		<% @pics.each do |pic| %>
			<div class="span3">
				<div class="boxy">
					<h5>ID: <%= pic.id %></h5>
					<h2>Hour: <%= pic.hour %></h2>
					<p />
					<%= image_tag pic.image %>
					<p />
					<h4>Emotion:</h4> 
						<p />
						<%= pic.emotion %>
					<p />
					<h4>Learned:</h4> 
					<p /><%= pic.learned %>
					<p />
				</div>
			</div>

		<%end %>
		<br />

				

app/views/pics/new.html.erb
<div class="span6 offset3 text-center">
	
<h1 class='custom-pic-header'>New Picture!</h1>
	<div class="boxy text-center">
	<%= simple_form_for @pic do |f| %>
		<%= f.input :hour %>
		<%= f.input :image, :as => :file %>
		<%= f.input :emotion %>
		<%= f.input :learned %>
		<%= submit_tag "Concede Scallywag!", :class => 'btn-primary btn-large' %>

	<% end %>
	</div>
</div>

app/views/staticpages/index.html.erb
<div class="span6 offset3">
	<div class="boxy">
	<h1 class="custom-font">Namaste! Mera naam Xaviera hai.</h1>


	<p class="custom-font">I'm having a ton of fun learning ruby on rails. Soon all the rubies shall be mine! Muahahaha.</p>
	<%= link_to('Begin Heist', new_pic_path, :class => 'btn btn-success btn-large') %>

	</div>
</div>